# Generated by Django 5.2.8 on 2025-12-01 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_room_no', models.CharField(max_length=50)),
                ('sleep_schedule', models.CharField(choices=[('Early', 'Early Bird (10 PM - 6 AM)'), ('Late', 'Night Owl (2 AM - 10 AM)')], max_length=10)),
                ('cleanliness_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 (Messy) to 5 (Super Clean)')),
                ('noise_tolerance', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 (Need Silence) to 5 (Party Mode)')),
                ('study_habit', models.CharField(choices=[('Morning', 'Morning'), ('Night', 'Night'), ('Mix', 'Mix')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
