# Generated by Django 5.2.8 on 2025-11-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeperType', models.CharField(max_length=255)),
                ('PersonalityType', models.CharField(max_length=255)),
                ('CleanlinessTolerance', models.CharField(max_length=255)),
                ('studyEnvironment', models.CharField(max_length=255)),
            ],
        ),
    ]
