# Generated by Django 5.2.8 on 2025-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='cleanliness_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='login',
            name='hostel_room',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='login',
            name='noise_tolerance',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='login',
            name='sleep_time',
            field=models.CharField(choices=[('early', 'Sleep Early'), ('late', 'Sleep Late'), ('mix', 'Mix / Flexible')], default='mix', max_length=10),
        ),
        migrations.AddField(
            model_name='login',
            name='study_habits',
            field=models.CharField(choices=[('morning', 'Morning'), ('night', 'Night'), ('mix', 'Mix')], default='mix', max_length=10),
        ),
    ]
