# Generated by Django 5.2.8 on 2025-12-06 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_roommateprofile_hostel_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommateprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: 03001234567', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '03001234567'. 11 digits allowed.", regex='^03\\d{9}$')]),
        ),
    ]
