# Generated by Django 5.2.8 on 2025-12-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_login_cleanliness_level_login_hostel_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='app.login'),
        ),
    ]
