# Generated by Django 5.2.8 on 2025-12-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_matchinteraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommateprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="roommateprofile",
            name="is_paying",
            field=models.BooleanField(default=False),
        ),
    ]
