# Generated by Django 5.2.8 on 2025-12-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_roommateprofile_gender_roommateprofile_is_paying"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roommateprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("", "Select Gender"), ("M", "Male"), ("F", "Female")],
                default="",
                max_length=1,
            ),
        ),
    ]
